"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Firecache = exports.CollectionUsedForDocumentOperation = exports.AlreadyExists = exports.NoData = void 0;
var firecache_js_1 = require("./firecache.js");
Object.defineProperty(exports, "Firecache", { enumerable: true, get: function () { return firecache_js_1.Firecache; } });
var errors_js_1 = require("./errors.js");
Object.defineProperty(exports, "NoData", { enumerable: true, get: function () { return errors_js_1.NoData; } });
Object.defineProperty(exports, "AlreadyExists", { enumerable: true, get: function () { return errors_js_1.AlreadyExists; } });
Object.defineProperty(exports, "CollectionUsedForDocumentOperation", { enumerable: true, get: function () { return errors_js_1.CollectionUsedForDocumentOperation; } });
exports.default = firecache_js_1.Firecache;
